import { Toaster } from '@/components/ui/sonner'
import './global.css'
import JotaiProvider from '@/components/jotaiProvider'
import OnlineStatusHandler from '@/components/common/online-status-handler'
import { ErrorBoundary } from 'next/dist/client/components/error-boundary'
import GlobalError from './global-error'

export const metadata = {
  title: 'Keyshade',
  description: 'Generated by create-nx-workspace'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}): React.JSX.Element {
  return (
    <html lang="en">
      <body>
        <ErrorBoundary errorComponent={GlobalError}>
          <JotaiProvider>
            <>
              <OnlineStatusHandler />
              {children}
            </>
          </JotaiProvider>
        </ErrorBoundary>
      </body>
      <Toaster richColors />
    </html>
  )
}
