# These are supported funding model platforms

open_collective: keyshade
custom: ["https://console.algora.io/bounties/new"]

# .github/funding.yml
github: keyshade-xyz
custom: ["https://github.com/sponsors/keyshade-xyz"]
