codecov:
  max_report_age: 24
  require_ci_to_pass: false

coverage:
  range: 50..90 # coverage lower than 50 is red, higher than 90 green, between color code

  status:
    project:
      default:
        enabled: false

    patch:
      default:
        enabled: false

flag_management:
  individual_flags:
    - name: web
      paths:
        - apps/web/
      carryforward: true
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 98%
    - name: api-e2e-tests
      paths:
        - apps/api/
      carryforward: true
      statuses:
        - type: project
          target: 85%
        - type: patch
          target: 98%
    - name: api-client
      paths:
        - packages/api-client/
      carryforward: true
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 98%
    - name: schema
      paths:
        - packages/schema/
      carryforward: true
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 98%
    - name: secret-scan
      paths:
        - packages/secret-scan/
      carryforward: true
      statuses:
        - type: project
          target: 80%
        - type: patch
          target: 98%