version: '3.9'

services:
  dev-db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keyshade_db
    volumes:
      - ./data:/var/lib/postgresql/data