export interface CreateProjectRequest {}
export interface CreateProjectResponse {}
export interface UpdateProjectRequest {}
export interface UpdateProjectResponse {}
export interface DeleteProjectRequest {}
export interface DeleteProjectResponse {}
export interface GetProjectRequest {}
export interface GetProjectResponse {}
export interface ForkProjectRequest {}
export interface ForkProjectResponse {}
export interface SyncProjectRequest {}
export interface SyncProjectResponse {}
export interface UnlinkProjectRequest {}
export interface UnlinkProjectResponse {}
export interface GetForkRequest {}
export interface GetForkResponse {}
export interface GetAllProjectsRequest {}
export interface GetAllProjectsResponse {}
