export interface CreateSecretRequest {}
export interface CreateSecretResponse {}
export interface UpdateSecretRequest {}
export interface UpdateSecretResponse {}
export interface DeleteSecretRequest {}
export interface DeleteSecretResponse {}
export interface RollBackSecretRequest {}
export interface RollBackSecretResponse {}
export interface getAllSecretsOfProjectRequest {}
export interface getAllSecretsOfProjectResponse {}
export interface getAllSecretsOfEnvironmentRequest {}
export interface getAllSecretsOfEnvironmentResponse {}
