export interface CreateVariableRequest {}
export interface CreateVariableResponse {}
export interface UpdateVariableRequest {}
export interface UpdateVariableResponse {}
export interface RollBackVariableRequest {}
export interface RollBackVariableResponse {}
export interface DeleteVariableRequest {}
export interface DeleteVariableResponse {}
export interface getAllVariablesOfProjectRequest {}
export interface getAllVariablesOfProjectResponse {}
export interface getAllVariablesOfEnvironmentRequest {}
export interface getAllVariablesOfEnvironmentResponse {}
