name: Auto Tag PR
on:
  pull_request:
    types: [opened, synchronize]
  pull_request_target:
    types: [opened, synchronize]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add labels
        run: |
          PR_TITLE=$(gh pr view ${{ github.event.pull_request.number }} --json title -q '.title')
          if [[ $PR_TITLE == *\[BREAKING\]* ]]; then
            gh pr label ${{ github.event.pull_request.number }} -l "type: breaking"
          elif [[ $PR_TITLE == chore* || $PR_TITLE == feat/* || $PR_TITLE == feature* || $PR_TITLE == fix* || $PR_TITLE == docs/* || $PR_TITLE == doc* || $PR_TITLE == patch* || $PR_TITLE == test/* || $PR_TITLE == tests* ]]; then
            LABEL="type:"$(echo $PR_TITLE | awk '{print tolower($0)}' | cut -d'/' -f1)
            gh pr label ${{ github.event.pull_request.number }} -l "$LABEL"
          else
            gh pr label ${{ github.event.pull_request.number }} -l "type: misc"
          fi
