name: Deploy CLI
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths: ['apps/cli/**', '.github/workflows/deploy-cli.yml', 'package.json']

jobs:
  publish:
    name: Publish CLI
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@keyshade'

      - name: Check versions
        id: check-versions
        run: |
          current_version=$(jq -r '.version' apps/cli/package.json)
          published_version=$(npm show @keyshade/cli version)

          if [ "$current_version" == "$published_version" ]; then
            echo "Published version of @keyshade/cli is same as the current version: $current_version. Skipping publish."
            exit 0
          fi

      - name: Get published version
        id: published_version
        run: echo "published_version=$(npm show @keyshade/cli version)" >> $GITHUB_ENV

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:cli

      - name: Authenticate with npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish
        run: cd apps/cli && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
