name: Docker Check

on:
  push:
    paths:
      - '**Dockerfile'
  pull_request:
    paths:
      - '**Dockerfile'
jobs:
  build-image-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -f apps/** .
