name: Issue PR Reminder

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  issue-pr-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          CREATE_PR_REMINDER_ENABLED: ${{ vars.CREATE_PR_REMINDER_ENABLED }}
          CREATE_PR_REMINDER_AFTER_DAYS: ${{ vars.CREATE_PR_REMINDER_AFTER_DAYS }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = 'keyshade-xyz';
            const repo = 'keyshade';
            const createPrReminderEnabled = process.env.CREATE_PR_REMINDER_ENABLED || false;
            const createPrReminderAfterDays = process.env.CREATE_PR_REMINDER_AFTER_DAYS || 2;
            const createPrReminderAfterMilliseconds = createPrReminderAfterDays * 24 * 60 * 60 * 1000;
            const now = Date.now();

            if(!createPrReminderEnabled) {
              console.log('!!! Dry run, there are no changes made !!!');
            }

            async function listOpenIssues() {
              const issues = [];
              let page = 1;
              let hasNextPage = true;

              while (hasNextPage) {
                const issuesResponse = await github.rest.issues.listForRepo({
                  owner,
                  repo,
                  state: 'open',
                  per_page: 100,
                  page
                });

                issues.push(...issuesResponse.data);

                hasNextPage = issuesResponse.headers.link && issuesResponse.headers.link.includes('rel="next"');
                page++;
              }

              return issues;
            }

            async function listIssueEvents(issue) {
              const allEvents = [];
              let page = 1;
              let hasNextPage = true;

              while (hasNextPage) {
                const issuesResponse = await github.rest.issues.listEventsForTimeline({
                  owner,
                  repo,
                  issue_number: issue.number,
                  per_page: 100,
                  page
                });

                allEvents.push(...issuesResponse.data);

                hasNextPage = issuesResponse.headers.link && issuesResponse.headers.link.includes('rel="next"');
                page++;
              }

              return allEvents.sort((a, b) => a.id > b.id);
            }

            async function listIssueComments(issue) {
              const allComments = [];
              let page = 1;
              let hasNextPage = true;

              while (hasNextPage) {
                const issuesResponse = await github.rest.issues.listComments({
                  owner,
                  repo,
                  issue_number: issue.number,
                  per_page: 100,
                  page
                });

                allComments.push(...issuesResponse.data);

                hasNextPage = issuesResponse.headers.link && issuesResponse.headers.link.includes('rel="next"');
                page++;
              }

              return allComments;
            }

            async function createPrReminders() {
              const issues = await listOpenIssues();

              for (const issue of issues) {
                const events = await listIssueEvents(issue);
                const pullRequests = events
                    .filter(event => event.event === 'cross-referenced')
                    .map(event => event.source.issue)
                    .filter(issue => issue && issue.pull_request);
                const comments = await listIssueComments(issue);

                for (const assignee of issue.assignees) {
                  // Check if assignee has already opened a PR
                  const assigneePullRequest = pullRequests.find(pullRequest => pullRequest.user.login === assignee.login);

                  if(assigneePullRequest) {
                    continue;
                  }

                  // Check if it is time to create a reminder
                  const assignedEvent = events.find(event => event.event === 'assigned' && event.assignee.login === assignee.login);                  
                  const issueAssignedAt = new Date(assignedEvent.created_at);
                  const createPrReminderAfter = new Date(issueAssignedAt.getTime() + createPrReminderAfterMilliseconds);

                  if (now < createPrReminderAfter) {
                    continue;
                  }

                  // Check if reminder has already been created
                  const reminder = `@${assignee.login}, please open a draft PR linking this issue!`;

                  if (comments.some(comment => comment.body === reminder)) {
                    continue;
                  }

                  // Create reminder
                  if(createPrReminderEnabled) {
                    await github.rest.issues.createComment({
                      owner,
                      repo,
                      issue_number: issue.number,
                      body: reminder
                    });
                  }

                  console.log(`Issue '${issue.number}' reminder created for: ${assignee.login}`);
                }
              }
            }

            await createPrReminders();