on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-web-release:
    runs-on: ubuntu-latest
    name: Build and push Web docker image for release
    if: ${{ startsWith(github.ref , 'refs/tags/') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t keyshade/keyshade-web:${{ github.ref_name }} keyshade/keyshade-web:latest -f ./apps/web/Dockerfile .

      - name: Push Docker image
        run: docker push keyshade/keyshade-web
